#  Copyright (c) 2012-2014, Pfadibewegung Schweiz. This file is part of
#  hitobito_pbs and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_pbs.

# Settings relevant for the jubla wagon
# Overrides settings from the main application
application:
  name: MiData PBS/MSdS/MSS
  logo:
    image: logo.svg
    width: 220
    height: 80
  languages:
    de: Deutsch
    fr: Français
    it: Italiano
  footer:
    links:
      de:
        "Informationen und Hilfe": https://www.scout.ch/de/pfadi-online/midata/abteilungsleitung
        "Datenschutz": https://www.scout.ch/de/pfadi-online/midata/abteilungsleitung/datennutzung/at_download/file
      fr:
        "Aide et assistance": https://www.scout.ch/fr/scout-online/midata/utilisateur/utilisateur?set_language=fr
        "Datenschutz": https://www.scout.ch/fr/scout-online/midata/utilisateur/utilisation_des_donnees_midata_msds_fr/at_download/file
      it:
        "Aiuto e assistenza": https://www.scout.ch/it/scout-online/midata/utente/utente?set_language=it
        "Datenschutz": https://www.scout.ch/it/scout-online/midata/utente/datennutzung_midata_pbs_it/at_download/file


# The person with this email has root access to everything
# This person should only be used by the operators of the application, not the customers.
# Initially, a password reset token may be mailed from the application to this address to set a password.
root_email: hitobito-pbs@puzzle.ch

<% mail_domain = ENV['RAILS_MAIL_DOMAIN'].presence ||
                 ENV['RAILS_HOST_NAME'].presence ||
                 'localhost' %>

email:
  # Sender for all emails sent by the application
  sender: <%= "MiData PBS/MSdS/MSS <noreply@#{mail_domain}>" %>

  camp:
    submit_recipient: lager@pbs.ch
    submit_abroad_recipient: auslandlager@pbs.ch

